---
- name: "Get Dell EMC OS10 Show system summary"
  dellos10_command:
    commands: ['show system | display-xml']
    provider: "{{ hostvars[item].cli }}"
  with_items: "{{ groups['all'] }}"
  register: show_system
- set_fact: 
     output:  "{{ output|default([])+ [{'inv_name': item.item, 'host': item.invocation.module_args.provider.host, 'stdout_show_system': item.stdout}] }}"
  loop: "{{ show_system.results }}"
- debug: var=output
- name: "show system network call to lib "
  show_system_network_summary:
    cli_responses: "{{ output}} "
    output_type: "{{ output_method if output_method is defined else 'json' }}"
  register: show_system_network_summary
- debug: var=show_system_network_summary

